// apps/web-app/src/components/ColorDot.svelte
<script lang="ts">
	import clsx from 'clsx';

	export let color: string | undefined = undefined;
</script>

<div
	class={clsx('w-3 h-3 rounded-full', {
		'bg-tag-red': color === 'red',
		'bg-tag-green': color === 'green',
		'bg-tag-blue': color === 'blue',
		'bg-tag-purple': color === 'purple',
		'bg-tag-yellow': color === 'yellow',
		'bg-tag-orange': color === 'orange',
		'bg-tag-pink': color === 'pink',
		'bg-tag-brown': color === 'brown',
		'bg-tag-light-gray': color === 'light-gray',
		'bg-tag-dark-gray': color === 'dark-gray'
	})}
></div>

// apps/web-app/components/ColorDot.vue
<template>
  <div :class="{
    'w-3 h-3 rounded-full': true,
    'bg-tag-red': props.color === 'red',
    'bg-tag-green': props.color === 'green',
    'bg-tag-blue': props.color === 'blue',
    'bg-tag-purple': props.color === 'purple',
    'bg-tag-yellow': props.color === 'yellow',
    'bg-tag-orange': props.color === 'orange',
    'bg-tag-pink': props.color === 'pink',
    'bg-tag-brown': props.color === 'brown',
    'bg-tag-light-gray': props.color === 'light-gray',
    'bg-tag-dark-gray': props.color === 'dark-gray'
  }"></div>
</template>

<script setup lang="ts">
const props = defineProps<{
  color?: string
}>();
</script>
