// app/src/components/Modal.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { teleport } from '../actions/teleport';
	import clsx from 'clsx';
	import { createEventDispatcher } from 'svelte';

	type ModalPosition = 'center' | 'center-top';

	export let showModal = false;
	export let position: ModalPosition = 'center-top';

	const dispatch = createEventDispatcher();

	let overlayRef: HTMLDivElement;

	function handleCloseModal(e: Event) {
		if (e.target === overlayRef) {
			dispatch('closeModal');
		}
	}

	function getPositionClass(): string {
		if (position === 'center-top') {
			return 'justify-center items-baseline pt-8';
		}

		return 'justify-center items-center';
	}
</script>

{#if showModal}
	<!-- svelte-ignore a11y-click-events-have-key-events -->
	<!-- svelte-ignore a11y-no-static-element-interactions -->
	<div
		bind:this={overlayRef}
		class={clsx('fixed w-full h-full bg-black z-10 inset-0 bg-opacity-25 flex', getPositionClass())}
		use:teleport={'teleport'}
		on:click={handleCloseModal}
	>
		<slot />
	</div>
{/if}

// apps/web-app/components/Modal.vue
<template>
  <Teleport to="#teleports">
    <div v-if="isOpen"
      :class="{
        'fixed inset-0 z-50 flex items-center justify-center bg-modal-overlay': true,
        'pt-8 justify-center items-baseline': position === 'center-top',
        'justify-center items-center': position === 'center'
      }">
      <div ref="modalRef">
        <slot />
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { onClickOutside } from '@vueuse/core';
type ModalPosition = 'center' | 'center-top';
const { currentModal, closeModal } = useModal();
const props = withDefaults(defineProps<{
  id: string
  position?: ModalPosition
}>(), {
  position: 'center-top'
});
const modalRef = ref<HTMLDivElement>();
const isOpen = ref(currentModal.value === props.id);

watch(() => currentModal.value, (newValue) => {
  isOpen.value = newValue === props.id;
});

onClickOutside(modalRef, () => {
  closeModal();
});
</script>
