// app/src/components/NotesView.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { notes, selectedNote, type Note } from '../store';
	import clsx from 'clsx';
	import { get } from 'svelte/store';
	import { goto } from '$app/navigation';
	import { onDestroy } from 'svelte';

	let filteredNotes: Note[] = [];

	const unsubscribe = notes.subscribe((value) => {
		filteredNotes = [...value];
	});

	function selectNote(note: Note): void {
		if ($selectedNote?.id !== note.id) {
			selectedNote.update(() => note);
		}
		goto(`/note/${note.id}`);
	}

	async function createNote(): Promise<void> {
		const lastID = await window.electron.createNote('A title', '');
		notes.update((items) => {
			items.push({ id: lastID, title: 'A title', content: '' });
			return items;
		});
	}

	function handleSearch(e: Event) {
		const searchText = (e.target as HTMLInputElement).value.toLowerCase();
		filteredNotes = $notes.filter((note) => note.title.toLowerCase().includes(searchText));
	}

	onDestroy(() => {
		unsubscribe();
	});

</script>

<div class="bg-slate-200 w-[240px] min-w-[240px] max-w-[240px]">
	<div class="p-4">
		<div class="flex justify-end">
			<button on:click={createNote} class="bg-slate-200 hover:bg-slate-300 p-2 rounded mb-4"
				><Icon icon="fa-solid:plus" /></button
			>
		</div>
		<input on:input={handleSearch} class="p-2 rounded mb-4 w-full" placeholder="Search..." />
		<div class="max-h-[434px] overflow-y-auto">
			{#each filteredNotes as note, index}
				<button
					class={clsx('block w-full text-left p-4 bg-slate-300 hover:bg-slate-400', {
						'rounded-t': index === 0,
						'rounded-b': index === get(notes).length - 1
					})}
					on:click={() => selectNote(note)}
				>
					{note.id}
					{note.title}
				</button>
			{/each}
		</div>
	</div>
</div>

// apps/web-app/components/NotesView.vue
<template>
  <div class="bg-bg w-[20rem] min-w-[20rem] border-r border-bg-border">
    <div>
      <div class="p-4">
        <div class="flex justify-end mb-4">
          <button @click="handleCreateNote" class="bg-bg text-text-primary p-2 rounded hover:bg-bg-hover">
            <Icon name="fa-solid:plus" />
          </button>
        </div>
        <SearchInput @search="handleSearch" placeholder="Search..." />

        <div v-if="selectedTags.length" class="mt-2 flex flex-wrap gap-1">
          <Chip v-for="filteredTag in selectedTags" :key="filteredTag.id" :text="filteredTag.name"
            :color="filteredTag.color" hasCloseBtn @close="removeSelectedTag(filteredTag.id)" />
        </div>
      </div>
      <div class="overflow-y-auto min-h-[calc(100vh-136px)] max-h-[calc(100vh-136px)]">
        <button v-for="(note) in filteredNotes" :key="note.id" :id="`note-${note.id}`"
          :class="{ 'block w-full text-left p-4 border-b border-bg-secondary text-base': true, 'bg-bg-secondary': +route.params.id === note.id, 'hover:bg-bg-secondary': +route.params.id !== note.id }"
          @click="selectNote(note)">
          <div class="mb-3 text-text-primary-emphasis">{{ note.title }}</div>
          <div class="flex flex-wrap gap-1">
            <Chip v-for="tag in note.tags ?? []" :key="tag.id" :text="tag.name" :color="tag.color" />
          </div>
          <ContextMenu :targetId="`note-${note.id}`"
            :actions="[{ label: 'Remove', action: () => handleShowRemoveNoteDialog(note) }]" />
        </button>
      </div>
    </div>
  </div>

  <ConfirmationDialog :id="MODAL_REMOVE_NOTE" @action="handleRemoveNote" />
</template>

<script setup lang="ts">
const { searchNotes, createNote, deleteNote, selectedTags, removeSelectedTag, tags, notes } = useNotes();
const { openModal } = useModal();
const { settings } = useSettings();
const router = useRouter();

const filteredNotes = ref<Note[]>([]);
const searchText = ref<string>('')
const noteToDelete = ref<Note | null>(null)
const route = useRoute()
const MODAL_REMOVE_NOTE = 'MODAL_REMOVE_NOTE';

watch([searchText, selectedTags, tags, settings, notes], () => {
  filteredNotes.value = searchNotes(searchText.value);
});

onMounted(() => {
  filteredNotes.value = searchNotes(searchText.value);
});

const handleCreateNote = async () => {
  await createNote();
  filteredNotes.value = searchNotes(searchText.value);
}

const handleSearch = (event: { text: string }) => {
  searchText.value = event.text;
  searchNotes(event.text);
}

const selectNote = (note: any) => {
  router.push(`/note/${note.id}`);
}

const handleShowRemoveNoteDialog = (note: Note) => {
  noteToDelete.value = note;
  openModal(MODAL_REMOVE_NOTE);
}

const handleRemoveNote = async () => {
  const note = noteToDelete.value;
  if (!note) {
    return;
  }

  await deleteNote(note.id);
  filteredNotes.value = searchNotes(searchText.value);
}
</script>
