// react-app/src/App.tsx
import NoteView from "./components/NoteView";
import NotesView from "./components/NotesView";
import Sidebar from "./components/Sidebar";

export default function App() {
  return (
    <div className="flex h-full">
      <Sidebar />

      <NotesView />

      <div className="flex-grow p-4">
        <NoteView />
      </div>
    </div>
  )
}

// apps/web-app2/app.vue
<template>
  <div class="flex h-full">
    <Sidebar />

    <NotesView />

    <div class="flex-grow bg-bg text-text-primary">
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
useHead({
  title: 'NoteX',
  meta: [
    {
      name: 'description',
      content: 'A note-taking app for developers'
    }
  ]
})
</script>
