// app/src/components/ContextMenu.svelte
<script lang="ts">
	import type { ContextMenuConfig } from '../interfaces/ContextMenu';

	export let actions: ContextMenuConfig[] = [];

	let pos = { x: 0, y: 0 };
	let menu = { w: 0, h: 0, y: 0 };
	let browser = { w: 0, h: 0, y: 0 };
	let showMenu = false;

	export function show(e: MouseEvent) {
		showMenu = true;
		browser = {
			w: window.innerWidth,
			h: window.innerHeight,
			y: 0,
		};
		pos = {
			x: e.clientX,
			y: e.clientY
		};

		if (browser.h - pos.y < menu.h) pos.y = pos.y - menu.h;
		if (browser.w - pos.x < menu.w) pos.x = pos.x - menu.w;
	}

	function onPageClick(e: Event) {
		showMenu = false;
	}

	function getContextMenuDimension(node: HTMLElement) {
		let height = node.offsetHeight;
		let width = node.offsetWidth;
		menu = {
			h: height,
			w: width,
			y: 0,
		};
	}

	export function hide() {
		showMenu = false;
	}

	function handleClickAction(e: Event, config: ContextMenuConfig) {
		e.preventDefault();
		e.stopImmediatePropagation();
		config?.action?.();
		showMenu = false;
	}

</script>

{#if showMenu}
	<nav use:getContextMenuDimension style="position: absolute; top:{pos.y}px; left:{pos.x}px">
		<ul class="border bg-slate-50 rounded">
			{#each actions as action}
				<li>
					<button class="p-4 hover:bg-slate-100 w-full text-start" on:click={(e) => handleClickAction(e, action)}>{action.label}</button>
				</li>
			{/each}
		</ul>
	</nav>
{/if}

<svelte:window on:click={onPageClick} />

// apps/web-app2/components/ContextMenu.vue
<template>
  <div>
    <nav v-if="showMenu" ref="component" :style="{ top: `${pos.y}px`, left: `${pos.x}px` }" class="absolute">
      <ul class="border border-bg-border bg-bg rounded">
        <li v-for="action in props.actions" :key="action.label">
          <button class="p-4 w-full text-left text-text-primary hover:bg-bg-hover" @click="handleClickAction(action)">
            {{ action.label }}
          </button>
        </li>
      </ul>
    </nav>
  </div>
</template>

<script setup lang="ts">
  const props = defineProps<{
    targetId: string;
    actions: ContextMenuConfig[];
  }>();

export interface ContextMenuConfig {
  label: string;
  action: () => void;
}

const showMenu = ref(false)
const pos = ref({ x: 0, y: 0 })
const component = ref<HTMLElement | null>(null)

const handleClickAction = (config: ContextMenuConfig) => {
  showMenu.value = false
  config.action();
}

const onPageClick = () => {
  showMenu.value = false
}

const onContextMenu = (event: MouseEvent) => {
  event.preventDefault();
  const targetEl = document.getElementById(props.targetId);
  if (targetEl && event.composedPath().includes(targetEl)) {
    pos.value = { x: event.clientX, y: event.clientY }
    showMenu.value = true     
  }
}

onMounted(() => {
  window.addEventListener('click', onPageClick)
  window.addEventListener('contextmenu', onContextMenu)
})

onBeforeUnmount(() => {
  window.removeEventListener('click', onPageClick)
  window.removeEventListener('contextmenu', onContextMenu)
})
</script>
