// apps/web-app/src/components/NotesView.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { notes, selectedNote, type Note, createNote, openModal, selectedTags, searchNotes, filteredNotes, deleteNote, fetchTags } from '../store';
	import clsx from 'clsx';
	import { goto } from '$app/navigation';
	import { onDestroy } from 'svelte';
	import ContextMenu from './ContextMenu.svelte';
	import ConfirmationDialog from './ConfirmationDialog.svelte';
	import Chip from './Chip.svelte';
	import SearchInput from './SearchInput.svelte';
	import { MODAL_REMOVE_NOTE } from '../constants/modal.constants';
	import { page } from '$app/stores';

	let noteToRemove: Note | undefined;
	let noteToSelect: Note | undefined;
	let searchText = '';
	let searchSection: HTMLDivElement;

	$: searchSectionHeight = searchSection?.clientHeight;

	const unsubscribe = notes.subscribe(() => {
		searchNotes(searchText);
	});

	selectedTags.subscribe(() => {
		searchNotes(searchText);
	});

	function selectNote(note: Note): void {
		if ($selectedNote?.id !== note.id) {
			selectedNote.update(() => note);
		}
		goto(`/note/${note.id}`);
	}

	async function handleCreateNote(): Promise<void> {
		const note = await createNote();
		if (note) {
			selectedNote.set(note);
			goto(`/note/${note.id}`);
		}
	}

	function handleSearch(e: Event) {
		if (e instanceof CustomEvent) {
			searchText = e.detail.text.toLowerCase();	
		}

		searchNotes(searchText);
	}

	function handleShowRemoveNoteDialog(note: Note, index: number): void {
		noteToRemove = note;
		noteToSelect = $filteredNotes[index + 1] ?? $filteredNotes[index - 1];
		openModal(MODAL_REMOVE_NOTE);
	}

	async function handleRemoveNote(): Promise<void> {
		if (!noteToRemove) {
			return;
		}

		await deleteNote(noteToRemove.id, noteToSelect);
		await fetchTags();
		// searchNotes(searchText);

		noteToRemove = undefined;
	}

	onDestroy(() => {
		unsubscribe();
	});
</script>

<div class="bg-bg w-[20rem] border-r border-bg-border">
    <div>
        <div bind:this={searchSection} class="p-4">
            <div class="flex justify-end mb-4">
                <button on:click={async () => await handleCreateNote()} class="bg-bg text-text-primary p-2 rounded hover:bg-bg-hover">
                    <Icon icon="fa-solid:plus" />
                </button>
            </div>
            <SearchInput on:search={handleSearch} placeholder="Search..." />

						{#if $selectedTags.length}
							<div class="mt-2 flex flex-wrap gap-1">
									{#each $selectedTags as filteredTag}
											<Chip
													text={filteredTag.name}
													color={filteredTag.color}
													hasCloseBtn
													on:close={() => selectedTags.update((tags) => tags.filter((tag) => tag.id !== filteredTag.id))}
											/>
									{/each}
							</div>
						{/if}
        </div>
        <div class="overflow-y-auto" style="height: calc(100vh - {searchSectionHeight}px);">
            {#each $filteredNotes as note, index}
                <button
                    id={`note-${note.id}`}
                    class={clsx('block w-full text-left p-4 border-b border-bg-secondary text-base', {
                        'bg-bg-secondary': +$page.params.id === note.id,
                        'hover:bg-bg-secondary': +$page.params.id !== note.id,
									})}
                    on:click={() => selectNote(note)}
                >
                    <div class="mb-3 text-text-primary-emphasis">{note.title}</div>
                    <div class="flex flex-wrap gap-1">
                        {#each (note.tags ?? []) as tag}
                            <Chip text={tag.name} color={tag.color} />
                        {/each}
                    </div>
                    
                    <ContextMenu
                        targetId={`note-${note.id}`}
                        actions={[{ label: 'Remove', action: () => handleShowRemoveNoteDialog(note, index) }]}
                    />
                </button>
            {/each}
        </div>
    </div>
</div>

<ConfirmationDialog
    id={MODAL_REMOVE_NOTE}
    on:action={async () => await handleRemoveNote()}
/>

// apps/web-app2/components/NotesView.vue
<template>
  <div class="bg-bg w-[20rem] border-r border-bg-border">
    <div>
      <div class="p-4">
        <div class="flex justify-end mb-4">
          <button @click="handleCreateNote" class="bg-bg text-text-primary p-2 rounded hover:bg-bg-hover">
            <Icon name="fa-solid:plus" />
          </button>
        </div>
        <SearchInput @search="handleSearch" placeholder="Search..." />

        <div v-if="selectedTags.length" class="mt-2 flex flex-wrap gap-1">
          <Chip v-for="filteredTag in selectedTags" :key="filteredTag.id" :text="filteredTag.name"
            :color="filteredTag.color" hasCloseBtn @close="removeSelectedTag(filteredTag.id)" />
        </div>
      </div>
      <div class="overflow-y-auto min-h-[calc(100vh-136px)] max-h-[calc(100vh-136px)]">
        <button v-for="(note) in filteredNotes" :key="note.id" :id="`note-${note.id}`"
          :class="{ 'block w-full text-left p-4 border-b border-bg-secondary text-base': true, 'bg-bg-secondary': +route.params.id === note.id, 'hover:bg-bg-secondary': +route.params.id !== note.id }"
          @click="selectNote(note)">
          <div class="mb-3 text-text-primary-emphasis">{{ note.title }}</div>
          <div class="flex flex-wrap gap-1">
            <Chip v-for="tag in note.tags ?? []" :key="tag.id" :text="tag.name" :color="tag.color" />
          </div>
          <ContextMenu :targetId="`note-${note.id}`"
            :actions="[{ label: 'Remove', action: () => handleShowRemoveNoteDialog(note) }]" />
        </button>
      </div>
    </div>
  </div>

  <ConfirmationDialog :id="MODAL_REMOVE_NOTE" @action="handleRemoveNote" />
</template>

<script setup lang="ts">
const { searchNotes, createNote, deleteNote, selectedTags, removeSelectedTag, tags } = useNotes();
const { openModal } = useModal();
const { settings } = useSettings();
const router = useRouter();

const filteredNotes = ref<Note[]>([]);
const searchText = ref<string>('')
const noteToDelete = ref<Note | null>(null)
const route = useRoute()
const MODAL_REMOVE_NOTE = 'MODAL_REMOVE_NOTE';

watch([searchText, selectedTags, tags, settings], () => {
  filteredNotes.value = searchNotes(searchText.value);
});

onMounted(() => {
  filteredNotes.value = searchNotes(searchText.value);
});

const handleCreateNote = async () => {
  await createNote();
}

const handleSearch = (event: { text: string }) => {
  searchText.value = event.text;
  searchNotes(event.text);
}

const selectNote = (note: any) => {
  router.push(`/note/${note.id}`);
}

const handleShowRemoveNoteDialog = (note: Note) => {
  noteToDelete.value = note;
  openModal(MODAL_REMOVE_NOTE);
}

const handleRemoveNote = async () => {
  const note = noteToDelete.value;
  if (!note) {
    return;
  }

  await deleteNote(note.id);
}
</script>
