// apps/web-app2/components/ConfirmationDialog.vue
<template>
  <Modal :id="id">
    <div
      class="inline-block rounded-[0.25rem] bg-bg border border-bg-border p-3 text-text-primary shadow-md z-20 min-w-[18.75rem]">
      <div class="flex items-center justify-between mb-8">
        <h2 class="text-[1.25rem] text-text-primary font-bold text-center">Confirm Action</h2>
        <button @click="closeModal" class="text-text-secondary hover:text-text-primary-hover">
          <Icon name="fa-solid:times" size="24" />
        </button>
      </div>
      <div class="min-w-[15.625rem] max-w-[21.875rem] text-text-secondary">
        <div v-if="description" class="mb-6">
          {{ description }}
        </div>
        <div class="flex justify-end gap-2">
          <Button @click="handleAction" variant="primary">Yes</Button>
          <Button @click="closeModal" variant="secondary">No</Button>
        </div>
      </div>
    </div>
  </Modal>
</template>

<script setup lang="ts">
const props = defineProps<{
  id: string;
  description?: string;
}>();

const { closeModal } = useModal();
const emits = defineEmits(['action']);

const description = ref(props.description || 'Are you sure you want to do this?');

const handleAction = () => {
  closeModal();
  emits('action');
};
</script>

// app/src/components/ConfirmationDialog.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import Modal from './Modal.svelte';
	import { createEventDispatcher } from 'svelte';

	export let showModal = false;
	export let description: string = 'Are you sure you want to this?';

	const dispatch = createEventDispatcher();

	function handleCloseModal() {
		dispatch('closeModal');
	}
</script>

<Modal {showModal} on:closeModal={handleCloseModal}>
	<!-- svelte-ignore a11y-click-events-have-key-events -->
	<!-- svelte-ignore a11y-no-static-element-interactions -->
	<div class="rounded bg-white p-3 shadow-lg inline-block z-20">
		<div class="flex items-center justify-between mb-8">
			<h2 class="text-xl font-bold text-center">Confirm Action</h2>
			<button on:click={handleCloseModal} class="hover:text-gray-600 text-black">
				<Icon icon="fa-solid:times" width="24" height="24" />
			</button>
		</div>
		<div class="min-w-[250px] max-w-[325px]">
			{#if description}
				<div class="mb-8">
					{description}
				</div>
			{/if}

			<div class="flex justify-end gap-2">
				<button class="py-2 px-3 bg-gray-200 hover:bg-gray-300 rounded cursor-pointer">No</button>
				<buttom class="py-2 px-3 bg-red-700 hover:bg-red-800 text-white rounded cursor-pointer">Yes</buttom>
			</div>
		</div>
	</div>
</Modal>
