// apps/web-app/components/Dialog.vue
<template>
  <Modal :id="id">
    <div
      class="inline-block rounded bg-bg text-text border border-bg-border p-6 z-20 min-w-[18.75rem] max-w-[31.25rem]">
      <button v-if="props.showHeader" @click="handleCloseModal"
        class="text-text-secondary hover:text-text-secondary-hover w-6 h-6 flex items-center justify-center absolute top-3 right-3">
        <Icon name="fa-solid:times" size="24" />
      </button>
      <slot />
    </div>
  </Modal>
</template>

<script setup lang="ts">
const props = defineProps<{
  id: string
  showHeader?: boolean
}>();
const { closeModal } = useModal();

const handleCloseModal = () => {
  closeModal()
}
</script>

// apps/web-app/src/components/Dialog.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { createEventDispatcher } from 'svelte';
	import Modal from './Modal.svelte';

	export let showModal = false;
	export let showHeader= true;

	const dispatch = createEventDispatcher();

	function closeModal() {
		dispatch('closeModal');
	}
</script>

<Modal {showModal} on:closeModal={closeModal}>
  <!-- svelte-ignore a11y-click-events-have-key-events -->
  <!-- svelte-ignore a11y-no-static-element-interactions -->
    <div
      class="rounded bg-bg text-text-secondary border-secondary p-3 shadow-lg inline-block z-20"
    >
      <div class="flex justify-end mb-3">
        {#if showHeader}
          <button on:click={closeModal} class="bg-bg text-text-secondary">
            <Icon icon="fa-solid:times" width="24" height="24" />
          </button>
        {/if}
      </div>
      <slot />
    </div>
</Modal>
