// apps/web-app/components/Modal.vue
<template>
  <Teleport to="#teleports">
    <div v-if="isOpen"
      :class="{
        'fixed inset-0 z-50 flex items-center justify-center bg-modal-overlay': true,
        'pt-8 justify-center items-baseline': position === 'center-top',
        'justify-center items-center': position === 'center'
      }">
      <div ref="modalRef">
        <slot />
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { onClickOutside } from '@vueuse/core';
type ModalPosition = 'center' | 'center-top';
const { currentModal, closeModal } = useModal();
const props = withDefaults(defineProps<{
  id: string
  position?: ModalPosition
}>(), {
  position: 'center-top'
});
const modalRef = ref<HTMLDivElement>();
const isOpen = ref(currentModal.value === props.id);

watch(() => currentModal.value, (newValue) => {
  isOpen.value = newValue === props.id;
});

onClickOutside(modalRef, () => {
  closeModal();
});
</script>

// apps/web-app/src/components/Modal.svelte
<script lang="ts">
	import { teleport } from '../actions/teleport';
	import clsx from 'clsx';
	import { currentModal } from '../store';
	import { clickOutside } from '../directives/clickOutside';
	import { createEventDispatcher, onDestroy } from 'svelte';

	type ModalPosition = 'center' | 'center-top';

	export let id: string;
	export let position: ModalPosition = 'center-top';

	let dispatcher = createEventDispatcher();

	function handleCloseModal() {
		dispatcher('closeModal');
	}

	const unsubscribe = currentModal.subscribe((value) => {
		if (!value) {
			handleCloseModal();
		}
	});

	onDestroy(() => {
		unsubscribe();
	});	

</script>

{#if $currentModal === id}
	<!-- svelte-ignore a11y-click-events-have-key-events -->
	<!-- svelte-ignore a11y-no-static-element-interactions -->
	<div
		class={clsx(
			'fixed inset-0 w-full h-full z-10 bg-modal-overlay flex',
			position === 'center-top' ? 'pt-8 justify-center items-baseline' : 'justify-center items-center'
		)}
		use:teleport={'teleport'}
		use:clickOutside={handleCloseModal}
	>
		<slot />
	</div>
{/if}
